language: objective-c
osx_image: xcode8.1
before_install: pod update
script: xcodebuild -workspace YFMediatorDemo.xcworkspace -scheme YFMediatorDemo -destination 'platform=iOS Simulator,name=iPhone 6' build
